#116 schematisation builder in project directory
threedi/hhnk-threedi-tools pull request #128
Opened 2024-12-06 14:58 UTC by Overmeen

Project maakt gebruik van bekende folder structuur, daar wat aanpassingen in gemaakt, bv een project.json toegevoegd. Project heeft een status

Zie ook interactie met plug-in https://github.com/threedi/hhnk-threedi-plugin/blob/%23176-UI-schematisation-builder---Export/hhnk_threedi_plugin/gui/schematisation_builder.py. Deze is bijna klaar voor deze sprint, alleen nog de daadwerkelijke export functie en omzetting naar hydamo hieraan toevoegen

2024-12-12 07:35 UTC, wvangerwen requested changes

2024-12-12 07:35 UTC, wvangerwen commented on hhnk_threedi_tools/core/folders_hydamo_validation.py
> +    def verify(self):
Ik heb in hrt een PR klaarstaan https://github.com/HHNK/hhnk-research-tools/pull/61 waarmee je dit niet op elke class erbij hoeft te zetten.

gebruik; `hrt.Folder.verify_exists(cls=self, keys=["dem", "hydamo", "rules"])`

2024-12-12 07:39 UTC, wvangerwen commented
De rest van de tekst was even weggevallen. Zou je de ruff fomatting ook kunnen draaien? Het makkelijkst is om hem in vscode op onSave in te stellen. Ik moet nog kijken dat we met iets van een hook draaien bij commits.

2024-12-12 10:24 UTC, Overmeen commented on hhnk_threedi_tools/core/project.py
> +            Path(folder).mkdir(parents=True, exist_ok=True)
Klopt, getest en niet nodig

2024-12-12 10:35 UTC, Overmeen commented on hhnk_threedi_tools/core/project.py
> +            self.__dict__.update(data)
ik snap niet helemaal wat je vraag is, maar het werkt iig goed

2024-12-12 10:46 UTC, Overmeen commented on hhnk_threedi_tools/core/folders_damo_to_hydamo_conversion.py
> +class SourcePaths:
Ga ik aan Folders toevoegen idd, dit had ik gecopy pasted van de modelbuilder, maar in ons geval niet nodig denk ik

2024-12-13 12:35 UTC, EvanderLaan approved these changes

2024-12-13 15:23 UTC, closed without merging