120 hydroobjecten exporteren damo
threedi/hhnk-threedi-tools pull request #130
Opened 2024-12-12 08:25 UTC by EvanderLaan

2024-12-13 15:25 UTC, Overmeen commented
PR voor 116 (project directory) - al goedgekeurd door Wietse - en 120 (damo export) - moet nog reviewed worden -

2024-12-13 15:30 UTC, wvanesse requested changes

2024-12-13 15:30 UTC, wvanesse commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +from hhnk_threedi_plugin.local_settings import DATABASES
import vanuit plugins, verkeerde kant op is hierargie modules?

2024-12-13 15:30 UTC, wvanesse commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +    # if instead of a model_extent, polder_name is given as input.
docstring

2024-12-13 15:30 UTC, wvanesse commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +        dict_gdfs_damo[table] = gdf_model
Waarom schrijven we niet naar geopackage?
We willen sowieso de export opslaan naar een DAMO.gpkg. Die moet uit de folders.py te halen zijn denk ik.
Nadeel van deze dict is ook als één van de tabellen faalt je ook alles kwijt bent.

2024-12-13 15:30 UTC, wvanesse commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +if __name__ == "__main__":
Losse test maken

2024-12-13 15:30 UTC, wvanesse commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +    bbox_model = box(*model_extent.total_bounds)
Het lijkt me netter om de bounding box functionaliteit toe te voegen aan research tools. Dan zorgen we ervoor dat die functie altijd werkt.

2025-04-08 12:21 UTC, EvanderLaan commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +    bbox_model = box(*model_extent.total_bounds)
Misschien goed om dit bespreken? Lijkt mij ook netter namelijk, maar volgens mij hadden we destijds besloten het voor nu hier te doen.

2025-04-08 12:22 UTC, EvanderLaan commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_exporter.py
> +from hhnk_threedi_plugin.local_settings import DATABASES
Aangepast, local_settings staan nu in zelfde map als script

2025-05-19 05:27 UTC, wvangerwen commented
Changes merged in #156

2025-05-19 05:27 UTC, closed without merging