121 transformatie naar hydamo
threedi/hhnk-threedi-tools pull request #131
Opened 2024-12-17 11:08 UTC by Overmeen

2024-12-17 14:30 UTC, wvanesse reviewed
Hi Stijn,

het ziet er profi uit. Ik kan er inhoudelijk niets veel op aanmerken. 
Heb je of kun je nog gebruik maken van dit: https://github.com/HetWaterschapshuis/HyDAMOValidatieModule/blob/ff9df5291b1f5522ac5b0e62260601c9acba64a1/hydamo_validation/datamodel.py#L295
Je weet dat we DAMO versie 2.4 draaien bij HHNK? Ik had begrepen dat er nog geen 2.4 is van HyDAMO, ik heb er  wel om gevraagd bij HWH, maar nog niets van gezien. Het verschil zal we niet zo groot zijn, zeker niet voor HydroObject.
Ik mis nog iets van een test of een voorbeeld hoe dit te gebruiken. Misschien kun me daar donderdag nog wat bij helpen?

2024-12-17 20:03 UTC, wvangerwen requested changes
Prima opzet, duidelijk wat er allemaal gebeurt. Een testdataset zou helpen, nog een paar opmerkingen.

2024-12-19 10:12 UTC, Overmeen commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_2_3/DAMO_23.xml
Ik heb dit destijds, anderhalf jaar geleden, ontvangen van via de mail van het waterschapshuis. We zouden even moeten onderzoeken of dit inmiddels online ergens aangeboden wordt, dan kunnen we ook 2.4 gebruiken ipv 2.3

2025-04-08 12:16 UTC, EvanderLaan commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_HyDAMO_converter.py
> +    def convert_column(self, column, column_name, layer_name):
Dit nu opgelost door de 'converter()' functie weg te halen, en het lopen over de layers in te voegen bij 'convert_layers()'. Hierdoor werd het wat mij betreft al leesbaarder (minder door verwijzingen binnen functies naar andere functies). Weet niet zeker of het op private zetten van de convert_column() functies, echt helpt bij de leesbaarheid, maar daar kunnen we het misschien nog over hebben?

2025-04-08 12:19 UTC, EvanderLaan commented on hhnk_threedi_tools/core/schematisation_builder/DAMO_HyDAMO_converter.py
Yes doen we nu

2025-05-19 05:27 UTC, wvangerwen commented
Changes merged in #156

2025-05-19 05:27 UTC, closed without merging