Model splitter fixes
threedi/hhnk-threedi-tools pull request #65
Opened 2023-09-26 06:39 UTC by d2hydro

Relates to https://github.com/threedi/hhnk-threedi-plugin/pull/97

2023-09-26 15:53 UTC, wvangerwen requested changes

2023-09-26 15:53 UTC, wvangerwen commented on hhnk_threedi_tools/resources/model_settings.xlsx
grid_space staat ook nog in model_settings_default. Mag maar bij 1 van de twee staan.

2023-09-27 09:20 UTC, d2hydro commented on hhnk_threedi_tools/resources/model_settings.xlsx
Heb hem eruit gehaald. Omdat jullie hem altijd op 20 hebben staan alleen in model_settings_default laten staan

2023-09-29 09:55 UTC, wvangerwen approved these changes

2023-09-29 11:34 UTC, merged